name: GitHub actions
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Install Doxygen
      run: |
        sudo apt-get install doxygen -y
    - name: cmake build
      run: |
        cmake -B build  .
        cmake --build build/doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/out/html